### ISSUE TITLE
Segfault in when using C++ 17

### ISSUE THREAD

**Issue by drobb257** [ouster-lidar/ouster_example#483] opened 2023-02-06 19:37 UTC
Building examples with C++ 17 creates a segfault due to the interaction between the non-standard (Boost?) optional and std::optional (tested with config_example.cpp) .

Setting this define to 0 fixes the issue by forcing the use of the Boost version
https://github.com/ouster-lidar/ouster_example/blob/202c536b358b537b3620964cea3919a24699a7dc/ouster_client/include/optional-lite/nonstd/optional.hpp#L86

It would be great to see this fixed to support C++ 17.  We're attempting to write a ROS2 driver and Galactic requires C++ 17. which makes it difficult to use the SDK directly.

Thanks for your help!

**Comment by Samahu** [comment] 2023-02-10 01:28
@drobb257 after spending a bit of time analyzing the structure of our cmake project, the issue is that you probably altered the cxx standard within  examples cmake file rather than altering the standard in the main cmake of the SDK. thus the client used a different cxx standard vs what the examples have used. Thus, different versions of **optional** where linked which effectively resulted in a segfault.

However, in ouster-ros (ros1) driver the project is explicitly was setting the standard to 14. I don't think it is needed here but it doesn't hurt, nonetheless, I did take out this configuration in my [upcoming update for ros1](https://github.com/ouster-lidar/ouster-ros/pull/52/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL29-L30), however, when porting the code to ros2 this cmake configuration has to be changed.
 
Closing the issue without taking any action in the client code.

**Closed by Samahu** 2023-02-10 01:28 UTC
Labels: bug
